<?php

namespace App\Constants;

class ConfigConstants
{
    public const ENCRYPTED_CONFIGS = [
        'services.ses.secret',
        'services.mailgun.secret',
        'services.facebook.client_secret',
        'services.google.client_secret',
        'services.twitter-oauth-2.client_secret',
        'services.bitbucket.client_secret',
        'services.github.client_secret',
        'services.linkedin-openid.client_secret',
        'services.gitlab.client_secret',
        'services.postmark.token',
        'services.resend.key',
        'recaptcha.api_secret_key',
        'services.twilio.sid',
        'services.twilio.token',
    ];

    public const OVERRIDABLE_CONFIGS = [
        'app.name',
        'app.description',
        'app.support_email',
        'app.date_format',
        'app.datetime_format',
        'app.google_tracking_id',
        'app.tracking_scripts',
        'mail.default',
        'mail.from.name',
        'mail.from.address',
        'services.ses.key',
        'services.ses.secret',
        'services.ses.region',
        'services.mailgun.domain',
        'services.mailgun.secret',
        'services.mailgun.endpoint',
        'services.facebook.client_id',
        'services.facebook.client_secret',
        'services.google.client_id',
        'services.google.client_secret',
        'services.twitter-oauth-2.client_id',
        'services.twitter-oauth-2.client_secret',
        'services.bitbucket.client_id',
        'services.bitbucket.client_secret',
        'services.github.client_id',
        'services.github.client_secret',
        'services.linkedin-openid.client_id',
        'services.linkedin-openid.client_secret',
        'services.gitlab.client_id',
        'services.gitlab.client_secret',
        'services.postmark.token',
        'services.resend.key',
        'app.social_links.facebook',
        'app.social_links.x',
        'app.social_links.linkedin-openid',
        'app.social_links.github',
        'app.social_links.instagram',
        'app.social_links.youtube',
        'app.social_links.discord',
        'mail.mailers.smtp.host',
        'mail.mailers.smtp.port',
        'mail.mailers.smtp.username',
        'mail.mailers.smtp.password',
        'app.recaptcha_enabled',
        'recaptcha.api_site_key',
        'recaptcha.api_secret_key',

        // Open Graphy
        'open-graphy.enabled',
        'open-graphy.template',
        'open-graphy.logo.enabled',
        'open-graphy.logo.location',
        'open-graphy.screenshot.enabled',
        'open-graphy.template_settings.strings.background',
        'open-graphy.template_settings.strings.stroke_color',
        'open-graphy.template_settings.strings.stroke_width',
        'open-graphy.template_settings.strings.text_color',
        'open-graphy.template_settings.stripes.start_color',
        'open-graphy.template_settings.stripes.end_color',
        'open-graphy.template_settings.stripes.text_color',
        'open-graphy.template_settings.sunny.start_color',
        'open-graphy.template_settings.sunny.end_color',
        'open-graphy.template_settings.sunny.text_color',
        'open-graphy.template_settings.verticals.start_color',
        'open-graphy.template_settings.verticals.mid_color',
        'open-graphy.template_settings.verticals.end_color',
        'open-graphy.template_settings.verticals.text_color',
        'open-graphy.template_settings.nodes.background',
        'open-graphy.template_settings.nodes.node_color',
        'open-graphy.template_settings.nodes.edge_color',
        'open-graphy.template_settings.nodes.text_color',

        // Cookie Consent
        'cookie-consent.enabled',

        // Authentication & Security
        'app.two_factor_auth_enabled',
        'app.otp_login_enabled',

        // Twilio
        'services.twilio.sid',
        'services.twilio.token',
        'services.twilio.from',
        'app.verification.default_provider',
    ];
}
